# Generated by Django 6.1.1 on 2026-10-01 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='endereço')),
                ('raw_title', models.CharField(blank=True, max_length=500, verbose_name='título original')),
                ('raw_text', models.TextField(blank=True, verbose_name='texto original')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recolhido em')),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name='extraído em')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_listings', to='catalog.source', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'anúncio recolhido',
                'verbose_name_plural': 'anúncios recolhidos',
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'url'), name='unique_raw_listing_per_source')],
            },
        ),
    ]
