# Generated by Django 6.1.1 on 2026-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_raw_listing_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlisting',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='motivo de exclusão'),
        ),
    ]
