# Generated by Django 6.1.1 on 2026-10-01 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nome')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='sítio web')),
                ('validated', models.BooleanField(default=False, help_text='Por exemplo, consta da lista de estruturas apoiadas pela DGArtes.', verbose_name='validada')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nome')),
                ('url', models.URLField(max_length=500, verbose_name='endereço')),
                ('tier', models.CharField(choices=[('A', 'A — primária'), ('B', 'B — quadro curado'), ('C', 'C — agregador aberto'), ('signal', 'Sinal')], max_length=10, verbose_name='nível de confiança')),
                ('method', models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('html', 'HTML')], max_length=10, verbose_name='método de recolha')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'fonte',
                'verbose_name_plural': 'fontes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('casting', 'Casting'), ('audition', 'Audição'), ('training', 'Formação'), ('grant', 'Apoio'), ('signal', 'No radar')], max_length=20, verbose_name='tipo')),
                ('pillar', models.CharField(choices=[('theatre', 'Teatro'), ('cinema', 'Cinema'), ('tv', 'Televisão'), ('marketing', 'Publicidade'), ('dubbing', 'Dobragem')], max_length=20, verbose_name='pilar')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='local')),
                ('region', models.CharField(choices=[('north', 'Norte'), ('centre', 'Centro'), ('south', 'Sul'), ('islands', 'Ilhas'), ('national', 'Nacional')], max_length=20, verbose_name='região')),
                ('remote', models.BooleanField(default=False, help_text='Self-tape ou online.', verbose_name='à distância')),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='idade mínima')),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='idade máxima')),
                ('gender', models.CharField(blank=True, choices=[('any', 'Qualquer'), ('female', 'Feminino'), ('male', 'Masculino'), ('other', 'Outro')], max_length=10, verbose_name='género')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='línguas')),
                ('pay', models.CharField(choices=[('paid', 'Pago'), ('unpaid', 'Não pago'), ('expenses', 'Só despesas'), ('unknown', 'Desconhecido')], default='unknown', max_length=10, verbose_name='remuneração')),
                ('fee_text', models.CharField(blank=True, max_length=200, verbose_name='detalhe da remuneração')),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Só para formação. 0 significa gratuita.', max_digits=8, null=True, verbose_name='preço (€)')),
                ('format', models.CharField(blank=True, choices=[('in_person', 'Presencial'), ('online', 'Online')], max_length=10, verbose_name='formato')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicada em')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vista pela primeira vez em')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('event_start', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('event_end', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('always_open', models.BooleanField(default=False, verbose_name='candidatura permanente')),
                ('expires_at_override', models.DateTimeField(blank=True, help_text='Substitui a data de expiração calculada.', null=True, verbose_name='expira em (manual)')),
                ('expires_at', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='expira em')),
                ('source_url', models.URLField(max_length=500, verbose_name='ligação original')),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='impressão digital')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='vista pela última vez em')),
                ('status', models.CharField(choices=[('pending_review', 'Por rever'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('withdrawn', 'Retirada')], db_index=True, default='pending_review', max_length=20, verbose_name='estado')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='catalog.organisation', verbose_name='organização')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='catalog.source', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
                'ordering': ['expires_at'],
            },
        ),
    ]
