# Generated by Django 6.1.1 on 2026-10-01 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Quem publica a oportunidade. Obrigatória para aprovar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='catalog.organisation', verbose_name='organização'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('organisation__isnull', False), _connector='OR'), name='approved_action_has_poster', violation_error_message='Uma ação aprovada tem de indicar quem a publica.'),
        ),
    ]
