# Generated by Django 6.1.1 on 2026-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_source_slug_api_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Tem atividade conhecida nos últimos dois anos (por exemplo, um apoio da DGArtes).', verbose_name='validada'),
        ),
    ]
