# Generated by Django 6.1.1 on 2026-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_organisation_validated_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='kind',
            field=models.CharField(blank=True, choices=[('company', 'Companhia de teatro'), ('producer', 'Produtora'), ('casting', 'Casting e agenciamento'), ('dubbing', 'Dobragem e voz'), ('venue', 'Teatro ou sala'), ('festival', 'Festival'), ('school', 'Escola e formação'), ('funder', 'Apoios e financiamento')], max_length=10, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'Norte'), ('centre', 'Centro'), ('south', 'Sul'), ('islands', 'Ilhas')], max_length=10, verbose_name='região'),
        ),
    ]
