# Generated by Django 6.1.1 on 2026-10-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('scheduled_for', models.DateTimeField(verbose_name='agendada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('subject', models.CharField(max_length=200, verbose_name='assunto')),
            ],
            options={
                'verbose_name': 'edição',
                'verbose_name_plural': 'edições',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('closing_soon', 'Últimos dias'), ('theatre', 'Teatro'), ('cinema', 'Cinema'), ('tv', 'Televisão'), ('marketing', 'Publicidade'), ('dubbing', 'Dobragem'), ('training', 'Formação'), ('grants', 'Apoios e oportunidades'), ('radar', 'No radar'), ('always_open', 'Candidaturas permanentes')], max_length=20, verbose_name='secção')),
                ('position', models.PositiveSmallIntegerField(verbose_name='posição')),
                ('was_new', models.BooleanField(default=False, verbose_name='novidade')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digest_items', to='catalog.action', verbose_name='ação')),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digest.digest', verbose_name='edição')),
            ],
            options={
                'verbose_name': 'item da edição',
                'verbose_name_plural': 'itens da edição',
                'ordering': ['digest', 'section', 'position'],
                'constraints': [models.UniqueConstraint(fields=('digest', 'action'), name='unique_action_per_digest')],
            },
        ),
    ]
