# Generated by Django 6.1.1 on 2026-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='scheduled_for',
            field=models.DateTimeField(unique=True, verbose_name='agendada para'),
        ),
    ]
